apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-microservice
spec:
  selector:
    matchLabels:
      app: red-ms
  replicas: 3
  template:
    metadata:
      labels:
        app: red-ms
    spec:
      containers:
      - name: red-ms
        imagePullPolicy: Always
        image: MediConnect/red
        ports:
        - containerPort: 8080
